version: "3.8"

services:
  webserver:
    env_file:
      - .env
    build: ./server
    container_name: bt_webserver
    ports: 
      - "5000:5000"
    depends_on:
      - db
  db:
    env_file:
      - .env
    container_name: bt_postgres
    image: postgres
    volumes:
      - data:/data/db

volumes:
  data: {}
